name: Deploy React App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build React app
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV
        run: |
          echo "APP=${github.event.repository.name}${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Packages
        run: rm -rf node_modules && yarn install
      - name: Build The App
        run: yarn build
      - name: Show some ENV
        run: echo ${{github.ref}}
      - name: Copy build folder into our server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{secrets.PASSPHRASE}}
          source: build
          target: ~/react-build-temp/{{ env.APP }}

      # - name: Clone the repo into server and copy build folder
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     passphrase: ${{secrets.PASSPHRASE}}
      #     script: |
      #       cd ~
      #       cd projects
      #       rm -rf ${{ github.event.repository.name }}
      #       git clone git@github.com:${{ github.event.repository.full_name }}.git
      #       cd ${{ github.event.repository.name }}
      #       git checkout dev
      #       git pull
      #       sh scripts/deploy.sh
